### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by tomciopp** [danschultzer/premailex#15]
I receive the following error when attempting to compile the most recent version of Premailex.

    == Compilation error in file lib/premailex/html_parser/meeseeks.ex ==
    ** (CompileError) lib/premailex/html_parser/meeseeks.ex:7: module Meeseeks.CSS is not loaded and could not be found

**Comment by danschultzer** [comment]
Sorry about that, I'll fix it ASAP.

**Comment by danschultzer** [comment]
I've retired `v0.2.0` and `v0.2.1` has been released. Unfortunately, I didn't test for compilation without `Meeseeks`, but it's working with my production app now 👍
