### ISSUE TITLE
Traverse function might not be working properly

### ISSUE THREAD

**Issue by devnacho** [danschultzer/premailex#2]
Hi @danschultzer, 

First of all, thanks for this library! 😀 

I'm inlining an email and there are some styles that are correctly inlined and some others have`[SPEC=n[..]`

As a reference this is the email(simplified) that's not working.
https://gist.github.com/devnacho/79af503a211d4ccc3aa471a8c6ab9672

Did you ever have this problem? I tried debugging as much as I can but I couldn't find a solution.

**Comment by danschultzer** [comment]
It's because I never build a proper CSS parser, it's [just regex](https://github.com/danschultzer/premailex/blob/master/lib/premailex/css_parser.ex#L6) that works most of the time. Let me see if I can adjust the regex to handle the `[SPEC=n]` cases, and then I'll figure out a proper parser later on 😁

**Comment by devnacho** [comment]
Thank you very much @danschultzer!

**Comment by danschultzer** [comment]
Using this PR in your mix.exs dependencies should work:

```
{:premailex, git: "https://github.com/danschultzer/premailex.git", branch: "handle-duplicate-dom"}
```

I'll release a new version later, as I'm still looking into if this can be fixed in a cleaner way. But you should be able to use the library by using the PR branch.

**Comment by danschultzer** [comment]
And as a note, it was not the CSS parser, but indeed the way the HTML DOM elements were traversed.

**Comment by devnacho** [comment]
Thank you very much Dan! It works perfect 👏

**Comment by danschultzer** [comment]
🎉

I've rewritten the traverse method, so it'll stop traversing after the first match. Pushed in version `0.1.2`. Thanks for letting me know about this bug @devnacho!

**Comment by devnacho** [comment]
Thanks a lot @danschultzer!!!
