### ISSUE TITLE
nth-child(even) not working

### ISSUE THREAD

**Issue by sb8244** [danschultzer/premailex#33]
This rule seems to be triggered for every row rather than even rows. It looks like it might be too complex of a rule for the parser, but I wanted to bring it to attention in case it's unexpected!

Thanks for your work on premailex.

```
.okr-section:nth-child(even) {
  background-color: #caddff;
}
```

**Comment by danschultzer** [comment]
This is most likely a limitation with Floki. You can try [switch the HTML parser out to Meeseeks](https://github.com/danschultzer/premailex#html-parser) and see if that resolves it. The CSS parser should use the full `.okr-section:nth-child(even)` selector.

**Comment by sb8244** [comment]
Thanks @danschultzer! I ended up switching to manual CSS class generation in my EEX template, and Floki is working well otherwise.
