### ISSUE TITLE
IE Conditional Comments Get Stripped

### ISSUE THREAD

**Issue by andykent** [danschultzer/premailex#36]
It's fairly common for emails to have to resort to IE conditional comments like this...

```html
<!--[if (gte mso 9)|(IE)]>
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr>
    <![endif]-->
```

I have tried with both the Floki and Meeseeks adapters and it seems like in both cases premailex is stripping the comments out. Is it possible to add support for keeping conditional comments intact in the output?

Thanks for the library, it's been working flawlessly for us in all other regards but this is a bit of a blocker.

**Comment by danschultzer** [comment]
Thanks!

Yeah, premailex strips all comments:

https://github.com/danschultzer/premailex/blob/88d6fc00342d1522e6406572070460053aa64c49/lib/premailex/util.ex#L47

I've opened a PR to fix this. Let me know if it works for you: #37

**Comment by andykent** [comment]
Amazing you are an absolute legend. 

I can confirm that this fixed the issue we were having perfectly and so quickly.

Thanks again so much for you help.

**Comment by andykent** [comment]
There is actually another conditional comments use case I've just hit but I think retaining it might be a bit more work because It's a hack to allow inverse conditional comments that I imagine is very confusing to parse. It looks like this...

```
<!--[if !mso]><!-- --><div>stuff hidden from IE</div><!--<![endif]-->
```

I wouldn't blame you if you don't want to even attempt to support this though. 

I think the changes needed would be...

- retain empty (whitespace only?) comments
- retain comments that start `<!--<![`

**Comment by danschultzer** [comment]
Hmm, yeah, it's because Floki/Meeseeks can't pick up on downlevel revealed comment because it's not [actually an XHTML comment](https://en.wikipedia.org/wiki/Conditional_comment). Instead of nested, it will just be seen as three sibling tags (two comments, and one div), and this is the valid interpretation for the DOM. There is no easy way to fix this unfortunately.

Conditional comments in HTML should probably be discouraged since IE9 was the last version to support it.

**Comment by andykent** [comment]
> Conditional comments in HTML should probably be discouraged since IE9 was the last version to support it.

Trust me I know! Unfortunately though Outlook still account for around 10% of email renders and it relies on the Word HTML renderer. https://litmus.com/blog/a-guide-to-rendering-differences-in-microsoft-outlook-clients

I totally get the desire to not have to try and support this at the library level though. I think my best bet might be to have some sort of magic conditional comment and then parse it out with a string replace after the prerender call. It's kind of yucky but it's likely the best option for now. 

Translate...

```
<!--[if INVERT !mso]>
<div>stuff hidden from IE</div>
<![endif INVERT]-->
```

into

```
<!--[if !mso]><!-- -->
<div>stuff hidden from IE</div>
<!--<![endif]-->
```

**Comment by danschultzer** [comment]
I was thinking about this, and it would work just as fine just catching the "<![endif]" comment. #38 adds support. Let me know if it works for you.

**Comment by andykent** [comment]
Yes, can't believe I didn't twig that. solves the issue 100%. Thanks so much. 🤗 

---

I'm not sure about the log statement though...

> Conditional comments are supported, but discouraged

I'm not sure it adds anything because it's not like there's an alternative we can push developers towards. In as much as this is an email support library and people wouldn't be using this functionality if it wasn't required to support Outlook rendering. You could just as easily say...

> inlining CSS attributes is supported, but discouraged.

As that is also functionality that is supported to please certain rendering clients.

Unfortunately though both these things are necessary evils when it comes to email templates so I'm not sure notifying people they are using conditional comments does much more than add noise to the logs.

**Comment by danschultzer** [comment]
You are right, and I don't see myself removing this feature anytime soon so it's unnecessary. `v0.3.7` released :rocket:

**Comment by andykent** [comment]
👏  Thanks again for your help with this.

**Comment by wosephjeber** [comment]
I just encountered this issue today, and I'm glad to see it's already been resolved! This library is a huge help, so thank you for your hard work on it!
