### ISSUE TITLE
Clobbers existing inline styles

### ISSUE THREAD

**Issue by dantswain** [danschultzer/premailex#39]
Hi!  Thanks for your work on this lib!  I'm evaluating using it to build emails and it looks really promising, except for one issue.  If there are any existing inline styles, they appear to get blanked out regardless of whatever css the parser finds.

Here's a simple reproduction case: 
```
Premailex.to_inline_css("<span style=\"width: 100%;\">Hello</span>")
"<span style=\"\">Hello</span>"
```

If this is not by design and you think it would be relatively easy to fix, I would be glad to help out if you can point me in the right direction.

**Comment by danschultzer** [comment]
Interesting, this only happens if there is no `<style>` tags:

```elixir
Premailex.to_inline_css("<style>span {color:#000;}</style><span style=\"width: 100%;\">Hello</span>")
<style>span {color:#000;}</style><span style=\"color:#000;width:100%;\">Hello</span>
```

I'll have to look through the code to see why this happens, but when do you experience this issue? Usually inline css styling would mean you do have a `<style>` or `<link>` tag.

**Comment by dantswain** [comment]
Interesting. I’ll try to come up with a minimal repro case because i definitely have style tags.

**Comment by danschultzer** [comment]
Fixed in master 😄
