### ISSUE TITLE
Elixir 1.11 Application boundary Warning for :inets

### ISSUE THREAD

**Issue by altdsoy** [danschultzer/premailex#55]
Hello Dan,

I saw you already updated in some kind with Elixir 1.11 which is great!
However as you might know there is a new check feature about applications boundaries https://elixir-lang.org/blog/2020/10/06/elixir-v1-11-0-released/#compiler-checks-application-boundaries
So i got a warning because of the use of `:httpc.request` here https://github.com/danschultzer/premailex/blob/1371fab96cd9d234960d252960d04fb0700dacd8/lib/premailex/http_adapter/httpc.ex#L18

You can either add `:httpc` in your `mix.exs` file (alongside other module you already excluded) like so (and reordered alphabetically):
```elixir
      xref: [exclude: [:certifi, :httpc, Meeseeks, Meeseeks.Document, Meeseeks.Selector.CSS, :ssl_verify_hostname]]
```

But I guess it could better convey intent to add `:inets` as a dependency in `deps` like so:
```elixir
defp deps do
    [
      {:floki, "~> 0.19"},
      {:meeseeks, "~> 0.11", optional: true},
      {:certifi, ">= 0.0.0", optional: true},
      {:ssl_verify_fun, ">= 0.0.0", optional: true},
      {:credo, "~> 1.4.0", only: [:dev, :test], runtime: false},
      {:ex_doc, ">= 0.0.0", only: :dev},
      {:inets}
    ]
  end
```

Another solution might be to add `:inets` as an `extra_applications` but I'm not sure it's relevant here.

I didn't make a PR for this because it's basically a oneliner and you are best placed to choose the correct fix (and also perform all the version bumps etc.)

Anyway, thanks for the lib..

_NB: As a side note.. I don't look into the details of how it supports CSS from files since I only used styles from the `head` but is this library able to support tailwind classes right now? I might be interested to implement that if not.._

_NB2: I also noticed that the CSS in the `head` is kept, why not get rid of the `head` tag altogether afterwards?_

**Comment by danschultzer** [comment]
Good call, thanks!

I think the first option is the best as it is you may want to build a release using another http adapter ignoring httpc. I've opened https://github.com/danschultzer/premailex/tree/ignore-httpc-missing-warning to resolve it, let me know if it works for you (`{:premailex, github: "danschultzer/premailex", ref: "ignore-httpc-missing-warning"}`)

> _NB: As a side note.. I don't look into the details of how it supports CSS from files since I only used styles from the `head` but is this library able to support tailwind classes right now? I might be interested to implement that if not.._

Premailex can pull CSS files (what `:httpc` is used for) defined anywhere the HTML content. It happens every time an e-mail is send out though.

There's a discussion on feeding the CSS directly to the premailex here https://github.com/danschultzer/premailex/issues/41, but I haven't yet figured out how that should work. It should probably be a compile time thing where you set a `:css` option that already has been parsed with `Premailex.CSSParser.parse/1`.

> _NB2: I also noticed that the CSS in the `head` is kept, why not get rid of the `head` tag altogether afterwards?_

It's a setting, off by default: https://hexdocs.pm/premailex/0.3.11/Premailex.HTMLInlineStyles.html#process/2

Just set `optimize: :all` or `optimize: :remove_style_tags`.

**Comment by altdsoy** [comment]
> let me know if it works for you (`{:premailex, github: "danschultzer/premailex", ref: "ignore-httpc-missing-warning"}`)

Yes I already tried this exact change and the warning hopefully goes away.
I think you can safely release a new version ;)

> Premailex can pull CSS files (what :httpc is used for) defined anywhere the HTML content. It happens every time an e-mail is send out though.

> There's a discussion on feeding the CSS directly to the premailex here #41, but I haven't yet figured out how that should work. It should probably be a compile time thing where you set a :css option that already has been parsed with Premailex.CSSParser.parse/1.

I was thinking about local css.. What's already "compiled" by the asset pipeline in the priv directory..
And often what's ending there doesn't depend on the asset pipeline (which bundler, if there is scss or postcss etc..) because in most cases the final CSS is going to be there anyway (in dev as well as in prod)..

> Just set optimize: :all or optimize: :remove_style_tags.

What is `:all` doing exactly vs `:remove_style_tags`?
Get rid of the entire `head` vs only the `style` tags?

BTW, Thank you for the details..

**Comment by danschultzer** [comment]
Great, it has been merged!

> What's already "compiled" by the asset pipeline in the priv directory

Yeah, this depends on your build process as the assets compile happens after the app has compiled with npm. You could load the file on runtime, or maybe set it up as part of the build process. In either case, I've opened #57 to make it simple to pass in any CSS you want to use for the HTML.

> What is `:all` doing exactly vs `:remove_style_tags`?
> Get rid of the entire `head` vs only the `style` tags?

There's no difference. The thought was to add in multiple optimization steps, e.g. removing newlines and whitespace.
